#!/bin/bash

DIR=/usr/local/lib/Radeon-tray

function copy_files {
    cp -vf "$PWD"/Radeon-tray.py "$DIR"
    cp -vrf "$PWD"/assets "$DIR"
    cp -vf "$PWD"/LICENSE "$DIR"
    cp -vf "$PWD"/utils.py "$DIR"
    cp -vf "$PWD"/last_power_method "$DIR"
    cp -vf "$PWD"/last_power_profile "$DIR"
    cp -vf "$PWD"/radeonpmserver.py "$DIR"
    cp -vf "$PWD"/radeontray /usr/local/bin
    cp -vf "$PWD"/radeonpmserver /usr/local/bin
    cp -vf "$PWD"/radeonpm.service /lib/systemd/system
}

if [ -d "$DIR" ] ; then
    echo "--> Copy files"
    copy_files
else
    echo "--> Create dir"
    mkdir "$DIR"
    echo "--> Copy files"
    copy_files
fi

echo "--> Reload daemons"
systemctl daemon-reload
echo "--> Enable service on startup"
systemctl enable radeonpm.service
echo "--> Start service"
systemctl start radeonpm.service